"""update model constraints

Revision ID: c96715c475bc
Revises: 4cc99b687aad
Create Date: 2024-07-07 16:07:06.807582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c96715c475bc'
down_revision = '4cc99b687aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('multiverse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('multiverse_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
